### ISSUE TITLE
Zooming feature

### ISSUE THREAD

**Issue by skadyrov** [diogobernardino/WilliamChart#24]
Hi Diogo,

Thanks for the awesome library! I am curious, are you planning to implement a zooming feature too? How difficult would that be to implement?

**Comment by diogobernardino** [comment]
Sorry @skadyrov but that's not in my list at all.

Without doing any research on that, so this is from the top of my head, perhaps by detecting a double click you can then decrease the window between Y min and Y max in order to get the feeling of zooming in. Though not sure this is the proper way of doing it.
