### ISSUE TITLE
LineBar example red warning

### ISSUE THREAD

**Issue by radeshf** [diogobernardino/williamchart#281]
i use example code to create line bar but give this error warning

`lineChart.gradientFillColors =
            intArrayOf(
                Color.parseColor("#81FFFFFF"),
                Color.TRANSPARENT
            )`

error warning
  

>  Size must be at least 2 and at most 2

it's work fine but give this error warning 
Android studio 4.0.1
library version 3.7.2
compileSdkVersion 30
buildToolsVersion 29.0.3

**Comment by diogobernardino** [comment]
Thanks for reporting. It shouldn't be the case, since the array only contains 2 elements, as it should. 
I tested it in v3.7.2, AS 4.1, compileSdkVersion 30, but I couldn't see the issue. Nevertheless, I've slightly improved the annotation. I will keep this issue open for now, see if anyone else is seeing the same issue.

**Comment by diogobernardino** [comment]
Not observed after improving annotation code.
