### ISSUE TITLE
Support CandleStickChart view

### ISSUE THREAD

**Issue by Archinamon** [diogobernardino/WilliamChart#29]
It would be great component if it will support candles. Even as "pro" version.

**Comment by diogobernardino** [comment]
Being realistic, I would never reach the point that I will actually go on and implement a CandleStickChart. As I have been staying, I will continue to focus in improving the charts I have at the moment (the most used ones) rather than creating every single type of chart. Moreover, I have built the library in a way that one can easily create his own model and view, extending ``ChartSet``/``ChartEntry`` and``ChartView`` respectively, and easily implement different charts. 
Said that I believe it makes no sense to keep this issue open. Sorry about that, I hope you can go on with other libraries that are mainly focused in quantity.
